/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PRINT_H_RPCGEN
#define _PRINT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define PRINTPROG 2200
#define PRINTVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PRINT 1
extern  char * print_1(void *, CLIENT *);
extern  char * print_1_svc(void *, struct svc_req *);
#define TOTAL 2
extern  int * total_1(int *, CLIENT *);
extern  int * total_1_svc(int *, struct svc_req *);
extern int printprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PRINT 1
extern  char * print_1();
extern  char * print_1_svc();
#define TOTAL 2
extern  int * total_1();
extern  int * total_1_svc();
extern int printprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PRINT_H_RPCGEN */
